site_name: SpiraDocs

repo_name: Inflectra
repo_url: https://www.inflectra.com
site_url: https://spiradoc.inflectra.com/

theme: 
  name: mkdocs
  custom_dir: inflectra_mkdocs
nav:
- Spira User Manual:
  - Functionality Overview: Spira_User_Manual\Functionality Overview.md
  - User/Product Management: Spira_User_Manual\User Product Management.md
  - Requirements Management: Spira_User_Manual\Requirements Management.md
  - Test Case Management: Spira_User_Manual\Test Case Management.md
  - Incident Tracking: Spira_User_Manual\Incident Tracking.md
  - Release Management: Spira_User_Manual\Release Management.md
  - Task Tracking: Spira_User_Manual\Task Tracking.md
  - Resource Tracking: Spira_User_Manual\Resource Tracking.md
  - Document Management: Spira_User_Manual\Document Management.md
  - Reports Center: Spira_User_Manual\Reports Center.md
  - Source Code: Spira_User_Manual\Source Code.md
  - Planning Board: Spira_User_Manual\Planning Board.md
  - Mobile Access: Spira_User_Manual\Mobile Access.md
  - Program Management: Spira_User_Manual\Program Management.md
  - Risk Management: Spira_User_Manual\Risks Management.md
  - 'Appendix 1: Keyboard Shortcuts': Spira_User_Manual\Appendix 1 Keyboard Shortcuts.md
- Quick Start Guides:
  - SpiraPlan:
    - Logging In: SpiraPlan_Quick_Start_Guide\Logging In and Selecting a Product.md
    - Define the Requirements: SpiraPlan_Quick_Start_Guide\Define the Requirements.md
    - Create Release & Iteration Plan: SpiraPlan_Quick_Start_Guide\Create the Release and Iteration Plan.md
    - Adding Requirement Tasks: SpiraPlan_Quick_Start_Guide\Adding Requirement Tasks.md
    - Adding Test Cases: SpiraPlan_Quick_Start_Guide\Adding the Test Cases.md
    - Planning the Sprint: SpiraPlan_Quick_Start_Guide\Planning the Sprint.md
    - Assigning Requirements & Tasks: SpiraPlan_Quick_Start_Guide\Assigning the Requirements & Tasks.md
    - Scheduling Testing Activities: SpiraPlan_Quick_Start_Guide\Scheduling the Testing Activities.md
    - Running Tests and Logging Incidents: SpiraPlan_Quick_Start_Guide\Running Tests and Logging Incidents.md
    - Triaging Issues and Defects: SpiraPlan_Quick_Start_Guide\Triaging Issues and Defects.md
    - Reviewing Your Product: SpiraPlan_Quick_Start_Guide\Reviewing Your Product.md
    - Reviewing A Program: SpiraPlan_Quick_Start_Guide\Reviewing A Program.md
  - SpiraTeam: 
    - Logging In: SpiraTeam_Quick_Start_Guide\Logging In and Selecting a Product.md
    - Define the Requirements: SpiraTeam_Quick_Start_Guide\Define the Requirements.md
    - Create Release & Iteration Plan: SpiraTeam_Quick_Start_Guide\Create the Release and Iteration Plan.md
    - Adding Requirement Tasks: SpiraTeam_Quick_Start_Guide\Adding Requirement Tasks.md
    - Adding Test Cases: SpiraTeam_Quick_Start_Guide\Adding the Test Cases.md
    - Planning the Sprint: SpiraTeam_Quick_Start_Guide\Planning the Sprint.md
    - Assigning Requirements & Tasks: SpiraTeam_Quick_Start_Guide\Assigning the Requirements & Tasks.md
    - Scheduling Testing Activities: SpiraTeam_Quick_Start_Guide\Scheduling the Testing Activities.md
    - Running Tests and Logging Incidents: SpiraTeam_Quick_Start_Guide\Running Tests and Logging Incidents.md
    - Triaging Issues and Defects: SpiraTeam_Quick_Start_Guide\Triaging Issues and Defects.md
    - Reviewing Your Product: SpiraTeam_Quick_Start_Guide\Reviewing Your Product.md
  - SpiraTest:
    - Logging In: SpiraTest_Quick_Start_Guide\Logging in and Selecting a Product.md
    - Define the Requirements: SpiraTest_Quick_Start_Guide\Define the Requirements.md
    - Create Release & Iteration Plan: SpiraTest_Quick_Start_Guide\Create the Release and Iteration Plan.md
    - Build the Test Plan: SpiraTest_Quick_Start_Guide\Build the Test Plan.md
    - Scheduling Testing Activities: SpiraTest_Quick_Start_Guide\Scheduling the Testing Activities.md
    - Running Tests and Logging Incidents: SpiraTest_Quick_Start_Guide\Running Tests and Logging Incidents.md
    - Triaging Issues and Defects: SpiraTest_Quick_Start_Guide\Triaging Issues and Defects.md
    - Reviewing Your Product: SpiraTest_Quick_Start_Guide\Reviewing Your Product.md
- Spira Admin Guide:
  - Installing Spira: Spira_Administration_Guide\Installing SpiraPlan.md
  - System Administration: Spira_Administration_Guide\System Administration.md
  - System:
    - Workspaces: Spira_Administration_Guide\System Workspaces.md
    - Users: Spira_Administration_Guide\System Users.md
    - System: Spira_Administration_Guide\System.md
    - Integration: Spira_Administration_Guide\System Integration.md
    - Reporting: Spira_Administration_Guide\System Reporting.md
  - Product: 
    - General Settings: Spira_Administration_Guide\Product General Settings.md
    - Users: Spira_Administration_Guide\Product Users.md
    - Planning: Spira_Administration_Guide\Product Planning.md
  - Template:
    - Requirements: Spira_Administration_Guide\Template Requirements.md
    - Releases: Spira_Administration_Guide\Template Releases.md
    - Documents: Spira_Administration_Guide\Template Documents.md
    - Test Cases: Spira_Administration_Guide\Template Test Cases.md
    - Incidents: Spira_Administration_Guide\Template Incidents.md
    - Tasks: Spira_Administration_Guide\Template Tasks.md
    - Risks: Spira_Administration_Guide\Template Risks.md
    - Custom Properties: Spira_Administration_Guide\Template Custom Properties.md
    - Notifications: Spira_Administration_Guide\Template Notifications.md
- AddOns and Integrations:
  - Testing:
    - NUnit: Unit_Testing_Integration\Integrating with NUnit.md
    - JUnit: Unit_Testing_Integration\Integrating with JUnit.md
    - TestNG: Unit_Testing_Integration\Integrating with TestNG.md
    - Selenium: Unit_Testing_Integration\Integrating with Selenium.md
    - PyUnit: Unit_Testing_Integration\Integrating with PyUnit.md
    - PyTest: Unit_Testing_Integration\Integrating with PyTest.md
    - MS-Test: Unit_Testing_Integration\Integrating with MS-Test.md
    - 'Ruby Test::Unit': Unit_Testing_Integration\Integrating with Ruby TestUnit.md
    - Perl TAP: Unit_Testing_Integration\Integrating with Perl TAP.md
    - PHPUnit: Unit_Testing_Integration\Integrating with PHPUnit.md
    - UnitJS & NodeJS: Unit_Testing_Integration\Integrating UnitJS & NodeJS.md
  - IDE Integration:
    - Visual Studio Code: IDE_Integration\Visual Studio Code.md
    - Visual Studio: IDE_Integration\Visual Studio.md
    - Jetbrains: IDE_Integration\Jetbrains IDEs.md
    - Eclipse: IDE_Integration\Eclipse  Mylyn.md
    - Visual Studio 2010: IDE_Integration\Visual Studio 2010.md
    - Visual Studio 2005-2008: IDE_Integration\Visual Studio 2005 - 2008.md
  - Bug Tracking/DataSync:
    - Setup: External_Bug_Tracking_Integration\Setting up Data Synchronization.md
    - JIRA 5+: External_Bug_Tracking_Integration\Using SpiraTeam with JIRA 5+.md
    - JIRA 3, 4: External_Bug_Tracking_Integration\Using SpiraTeam with JIRA 3  4.md
    - Bugzilla: External_Bug_Tracking_Integration\Using SpiraTest with Bugzilla.md
    - MS-TFS: External_Bug_Tracking_Integration\Using SpiraTest with MS-TFS.md
    - FogBugz: External_Bug_Tracking_Integration\Using SpiraTest with FogBugz.md
    - Mantis: External_Bug_Tracking_Integration\Using SpiraTeam with Mantis.md
    - ClearQuest: External_Bug_Tracking_Integration\Using SpiraTeam with ClearQuest.md
    - RTC: External_Bug_Tracking_Integration\Using SpiraTeam with IBM RTC.md
    - Axosoft: External_Bug_Tracking_Integration\Using Spira with Axosoft 14+.md
    - Redmine: External_Bug_Tracking_Integration\Using SpiraTeam with Redmine.md
    - VersionOne: External_Bug_Tracking_Integration\Using Spira with VersionOne.md
    - OnTime: External_Bug_Tracking_Integration\Using Spira with OnTime 11.md
    - GitHub: External_Bug_Tracking_Integration\Using Spira with GitHub.md
    - GitLab: External_Bug_Tracking_Integration\Using Spira with GitLab.md
    - ServiceNow: External_Bug_Tracking_Integration\Using Spira with ServiceNow.md
  - VCS: 
    - Git: Version_Control_Integration\Integrating with Git.md
    - Mercurial: Version_Control_Integration\Integrating with Mercurial.md
    - Subversion: Version_Control_Integration\Integrating with Subversion.md
    - Perforce: Version_Control_Integration\Integrating with Perforce.md
    - TFS: Version_Control_Integration\Integrating with TFS.md
    - VSS: Version_Control_Integration\Integrating with VSS.md
    - CVS: Version_Control_Integration\Integrating with CVS.md
  - Email:
    - Installing: Email_Integration\Installing the Email Integration Service.md
    - Configuring: Email_Integration\Configuring the Email Integration Service.md
    - Using: Email_Integration\Using the Email Integration Service with SpiraTeam.md
  - Help Desk:
    - KronoDesk: Help_Desk_Integration\KronoDesk.md
    - Zendesk: Help_Desk_Integration\Zendesk.md
  - Migration: 
    - Excel: Migration_and_Integration\Importing from Microsoft Excel.md
    - Excel (Office 365): Migration_and_Integration\Importing from Microsoft Excel (Office365).md
    - Google Sheets: Migration_and_Integration\Importing from Google Sheets.md
    - Microsoft Word: Migration_and_Integration\Importing from Microsoft Word.md
    - Microsoft Project: Migration_and_Integration\Importing from Microsoft Project.md
    - HP QualityCenter: Migration_and_Integration\Migrating from HP QualityCenter.md
    - Project Backup and Migration: Migration_and_Integration\Project Backup and Migration.md
    - MS Test Manager: Migration_and_Integration\Migrating from MS Test Manager.md
    - HP ALM: Migration_and_Integration\Migrating from HP ALM.md
    - TestRail: Migration_and_Integration\Migrating from TestRail.md
    - TestLink: Migration_and_Integration\Migrating from TestLink.md
  - Build Servers:
    - Jenkins/Hudson: Build_Server_Integration\Jenkins  Hudson.md
    - JetBrains TeamCity: Build_Server_Integration\JetBrains TeamCity.md
    - Azure DevOps Pipelines: Build_Server_Integration\Microsoft Azure DevOps Pipelines.md
    - Atlassian Bamboo: Build_Server_Integration\Atlassian Bamboo.md
  - Requirements:
    - RequisitePro: Requirements_Management_Integration\Importing From RequisitePro.md
    - EnterpriseArchitect: Requirements_Management_Integration\Importing From EnterpriseArchitect.md
    - Jama Contour: Requirements_Management_Integration\Importing From Jama Contour.md
    - VersionOne: Requirements_Management_Integration\Importing From VersionOne.md
    - DOORS: Requirements_Management_Integration\Importing From DOORS.md
  - TaraVault:
    - Activating: TaraVault_User_Manual\Activating TaraVault.md
    - Provisioning Projects & Users: TaraVault_User_Manual\Provisioning Projects & Users.md
    - Using Git: TaraVault_User_Manual\Using Git.md
    - Using Subversion: TaraVault_User_Manual\Using Subversion.md
  - RemoteLaunch:
    - Guide: RemoteLaunch_User_Guide\RemoteLaunch Guide.md
    - HP UFT/QTP: RemoteLaunch_User_Guide\HP UFT  QTP.md
    - SmarteScript: RemoteLaunch_User_Guide\SmarteScript.md
    - TestComplete: RemoteLaunch_User_Guide\TestComplete.md
    - Selenium: RemoteLaunch_User_Guide\Selenium.md
    - Squish: RemoteLaunch_User_Guide\Squish.md
    - Command-Line: RemoteLaunch_User_Guide\Command-Line.md
    - LoadRunner: RemoteLaunch_User_Guide\LoadRunner.md
    - SoapUI: RemoteLaunch_User_Guide\SoapUI.md
    - FitNesse: RemoteLaunch_User_Guide\FitNesse.md
    - NeoLoad: RemoteLaunch_User_Guide\NeoLoad.md
    - TestPartner: RemoteLaunch_User_Guide\TestPartner.md
    - BadBoy: RemoteLaunch_User_Guide\BadBoy.md
    - JMeter: RemoteLaunch_User_Guide\JMeter.md
    - Ranorex: RemoteLaunch_User_Guide\Ranorex.md
    - Rational Functional Tester: RemoteLaunch_User_Guide\Rational Functional Tester.md
    - TestingAnywhere: RemoteLaunch_User_Guide\TestingAnywhere.md
    - Worksoft Certify: RemoteLaunch_User_Guide\Worksoft Certify.md
    - ZAPTEST: RemoteLaunch_User_Guide\ZAPTEST.md